apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  SERVER_PORT: {{ .Values.configMap.serverPort | quote }}
  KEYCLOAK_PUBLIC_KEY: {{ .Values.configMap.keycloakPublicKey | quote }}
  JOBMANAGER_URL: {{ .Values.configMap.jobManagerUrl | quote }}
